name: Additional Issue Handling

on:
  issues:
    types: [opened]
env:
  # Setting an environment variable with the value of a configuration variable
  token: ${{ vars.TOKEN }}


jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically add labels and assignees
        uses: actions/github-script@v7
        with:
          #github-token: $token
          result-encoding: string
          debug: true
          script: |

            github.rest.issues.create({
              owner: "daviddsp",
              repo: "daviddsp/repo1",
              title: "${{ github.event.issue.title }}",
              body: "${{ github.event.issue.body }}"
            })
