name: Additional Issue Handling

on:
  issues:
    types: [opened]


jobs:
  handle-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically add labels and assignees
        uses: actions/github-script@v7
        with:
          result-encoding: string
          debug: true
          script: |
            
            github.rest.issues.create({
              owner: "daviddsp",
              repo: "repo1",
              title: "Test",
              body: "Test"
            })
        env: # Or as an environment variable
          token: ${{ secrets.TOKEN }}
          
